name: JP-Status

on:
  push:
    branches: master # Only trigger on master
    paths-ignore: # Don't trigger on files that are updated by the CI or other non-breaking files
    - 'tools/**'
    - '*.md'
    - '.gitignore'
    - 'CppProperties.json'
  pull_request:
    branches: master # Only trigger on master
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildjp:
    
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Depedencies
        run: |
          sudo apt update
          sudo apt install binutils-mips-linux-gnu make libcapstone-dev
          wget https://github.com/n64decomp/qemu-irix/releases/download/v2.11-deb/qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb
          sudo dpkg -i qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb

      - name: Get US File
        env:
          FILE_US: ${{ secrets.SECRET_FILE_US  }}
        run: wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -O baserom.u.z64 $FILE_US
      
      - name: Get JP File
        env:
          FILE_JP: ${{ secrets.SECRET_FILE_JP  }}
        run: wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -O baserom.j.z64 $FILE_JP

      - name: Extract US Assets
        run: ./scripts/extract_baserom.u.sh

      - name: Extract JP Assets
        run: ./scripts/extract_diff.j.sh

      - name: Make JP 
        run: make all -j IDO_RECOMP=YES VERSION=JP VERBOSE=1
          
      - name: Make report
        run: make -C tools/report
        
      - name: Stats
        run: python3 tools/ge-stats.py --version jp --report

